/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/05.glb -o src/components/three/Home_v5.jsx 
*/

import React from 'react'
import { MeshStandardMaterial } from 'three'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3D/16.glb')

  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])


  return (
<group {...props} dispose={null}>
      <primitive object={nodes.root} />
      <primitive object={nodes['MCH-torsoparent']} />
      <primitive object={nodes['MCH-hand_ikparentL']} />
      <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
      <primitive object={nodes['MCH-hand_ikparentR']} />
      <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
      <primitive object={nodes['MCH-foot_ikparentL']} />
      <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
      <primitive object={nodes['MCH-foot_ikparentR']} />
      <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
      <mesh geometry={nodes.ground.geometry} material={nodes.ground.material} rotation={[-Math.PI, 0, 0]} scale={[-1.35, -0.617, -1.866]} />
      <skinnedMesh geometry={nodes.Bady.geometry} material={materials.m_chat} skeleton={nodes.Bady.skeleton} position={[122.294, 1.896, -19.503]} rotation={[0, 1.143, 0]} scale={3.681} />
      <skinnedMesh geometry={nodes.Bady001.geometry} material={materials.m_chat} skeleton={nodes.Bady001.skeleton} position={[122.294, 1.896, -19.503]} rotation={[0, 1.143, 0]} scale={3.681} />
      <skinnedMesh geometry={nodes.Cube004.geometry} material={materials.m_chat} skeleton={nodes.Cube004.skeleton} position={[122.294, 1.896, -19.503]} rotation={[0, 1.143, 0]} scale={3.681} />
      <skinnedMesh geometry={nodes.Cylinder.geometry} material={materials.m_chat} skeleton={nodes.Cylinder.skeleton} position={[122.294, 1.896, -19.503]} rotation={[0, 1.143, 0]} scale={3.681} />
      <skinnedMesh geometry={nodes.Cylinder001.geometry} material={materials.m_chat} skeleton={nodes.Cylinder001.skeleton} position={[122.294, 1.896, -19.503]} rotation={[0, 1.143, 0]} scale={3.681} />
      <skinnedMesh geometry={nodes.eyes.geometry} material={materials['Material.002']} skeleton={nodes.eyes.skeleton} position={[122.294, 1.896, -19.503]} rotation={[0, 1.143, 0]} scale={3.681} />
      <group position={[122.294, 1.896, -19.503]} rotation={[0, 1.143, 0]} scale={3.681}>
        <skinnedMesh geometry={nodes.Cube004_1.geometry} material={materials.m_chat} skeleton={nodes.Cube004_1.skeleton} />
        <skinnedMesh geometry={nodes.Cube004_2.geometry} material={materials.Material} skeleton={nodes.Cube004_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/05.glb')
