/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/34-03.glb -o src/components/three/Home_v6.jsx 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { usePomodoroTimer } from '../stoer/usePomodoroTimer'
import * as THREE from 'three'

export function Sunsevven(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3D/34-03.glb')
  const { actions } = useAnimations(animations, group)

  const status = usePomodoroTimer((s) => s.status)

  /*----------------------------------*
   * 🔥 移植舊版的「focus 播動畫一次」邏輯
   *----------------------------------*/
  useEffect(() => {
    if (!actions) return

    if (status === 'focus') {
      const first = Object.values(actions)[0] // 第一個動畫

      if (first) {
        // 播一次 → 播到最後停住
        first.setLoop(THREE.LoopOnce, 1)
        first.clampWhenFinished = true

        first.reset().fadeIn(1).play()
      }
    }
  }, [status, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="ground" geometry={nodes.ground.geometry} material={materials['BG-2']} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.Material} position={[-50.33, -3.351, 19.85]} rotation={[0, 0, -Math.PI / 2]} scale={0.108} />
        <mesh name="the_way" geometry={nodes.the_way.geometry} material={materials['Material.032']} />
        <mesh name="Railway" geometry={nodes.Railway.geometry} material={materials['BG-2']} position={[-6.286, 1.496, 2.086]} scale={0.137} />
        <mesh name="Railway001" geometry={nodes.Railway001.geometry} material={materials['Material.032']} position={[-6.327, 5.957, 2.337]} scale={0.137} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Ari} position={[-8.399, 4.897, -13.432]} rotation={[0, -0.146, 0]} scale={7.659} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.W2} position={[36.951, 3.125, -9.841]} rotation={[-Math.PI, 0.462, 0]} scale={4.698} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[37.694, 3.416, 4.672]} rotation={[0, -0.436, 0]} scale={[1.851, 0.737, 0.137]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['BG-2']} position={[23.977, -1.01, 2.794]} scale={[0.137, 3.952, 0.137]} />
        <group name="Cube004" position={[34.814, 0, 11.093]} rotation={[0, -0.419, 0]}>
          <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials.EX} />
          <mesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} material={materials['Material.001']} />
        </group>
        <mesh name="立方體" geometry={nodes.立方體.geometry} material={materials.Ari} position={[5.657, 6.801, 16.593]} rotation={[0, 0.699, 0]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['BG-2']} position={[0.106, -1.142, 9.274]} rotation={[0, -0.873, 0]} scale={[1, 0.423, 1]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['BG-2']} position={[-12.83, -1.142, -5.031]} rotation={[0, -0.873, 0]} scale={[1, 0.423, 1]} />
        {/* <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[-2.201, 8.529, 6.368]} rotation={[0, -0.885, 0]} /> */}
        {/* <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-3.332, 8.529, 6.852]} rotation={[0, -0.885, 0]} /> */}
      </group>
    </group>
  )
}

useGLTF.preload('/3D/34-03.glb')
